# Generated by Django 5.1 on 2024-08-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
