# Generated by Django 5.1 on 2025-01-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
